apiVersion: v1
kind: Application
metadata:
  name: techtrends-staging
  namespace: staging
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: techtrends
  source:
    helm:
      valueFiles:
      - values-staging.yaml 
    path: project/helm
    repoURL: https://github.com/sireeben/nd064_course_1
    targetRevision: HEAD
