apiVersion: v1
kind: Application
metadata:
  name: techtrends-prod
  namespace: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: techtrends
  source:
    helm:
      valueFiles:
      - values-prod.yaml 
    path: project/helm
    repoURL: https://github.com/sireeben/nd064_course_1
    targetRevision: HEAD
